import { useEffect, useRef, useState } from "react";
import { ArrowUp, Bot, MessageCircle, RotateCcw } from "lucide-react";
import type { ChatMessage } from "@shared/portfolio-chat";

const starters = [
  { label: "Java backend fit", prompt: "Why is Shashank a strong Java backend candidate?" },
  { label: "OpsPilot in 30 seconds", prompt: "Explain OpsPilot-AI in 30 seconds." },
  { label: "9X internship work", prompt: "What did Shashank work on at 9X IT Solutions?" },
  { label: "Android experience", prompt: "Which projects show Android experience?" },
];

function SafeText({ text }: { text: string }) {
  const inline = (content: string) => content.split(/(\*\*[^*]+\*\*|\[[^\]]+\]\([^)]+\))/g).map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>;
    const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (link) { try { const url = new URL(link[2]); if (!["http:", "https:", "mailto:"].includes(url.protocol)) throw new Error(); const external = url.protocol !== "mailto:"; return <a key={index} href={url.href} target={external ? "_blank" : undefined} rel={external ? "noopener noreferrer" : undefined} className="font-semibold text-[#b83216] underline decoration-[#f04b23]/40 underline-offset-2 hover:decoration-[#f04b23] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23]">{link[1]}</a>; } catch { return <span key={index}>{part}</span>; } }
    return <span key={index}>{part}</span>;
  });
  return <div className="space-y-2">{text.split("\n").map((line, index) => { const bullet = /^[-*]\s+/.test(line); const content = line.replace(/^[-*]\s+/, ""); return bullet ? <div key={index} className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#f04b23]"/><p>{inline(content)}</p></div> : line ? <p key={index}>{inline(content)}</p> : <div key={index} className="h-1"/>; })}</div>;
}

export function ChatLauncher() {
  const [chatVisible, setChatVisible] = useState(false);
  useEffect(() => { const chat = document.getElementById("chat"); if (!chat) return; const observer = new IntersectionObserver(([entry]) => setChatVisible(entry.isIntersecting && entry.intersectionRatio > .12), { threshold: [.12, .3] }); observer.observe(chat); return () => observer.disconnect(); }, []);
  const activate = () => { const section = document.getElementById("chat"); const rect = section?.getBoundingClientRect(); const near = Boolean(rect && rect.top < 120 && rect.bottom > 180); if (!near) section?.scrollIntoView({ behavior: "smooth", block: "start" }); window.setTimeout(() => window.dispatchEvent(new Event("portfolio-chat-focus")), near ? 0 : 700); };
  return <button type="button" onClick={activate} aria-label="Ask about Shashank" title="Ask about Shashank" aria-hidden={chatVisible} tabIndex={chatVisible ? -1 : 0} className={`group fixed bottom-[calc(1rem+env(safe-area-inset-bottom))] right-4 z-[70] grid h-[54px] w-[54px] place-items-center rounded-[20px] bg-[#f04b23] text-white shadow-[0_12px_28px_rgba(73,35,21,.28)] transition duration-200 hover:-translate-y-1 hover:bg-[#dc401d] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f04b23] sm:bottom-[calc(1.5rem+env(safe-area-inset-bottom))] sm:right-6 sm:h-[60px] sm:w-[60px] sm:rounded-[22px] ${chatVisible ? "pointer-events-none translate-y-3 scale-90 opacity-0" : "opacity-100"}`}><MessageCircle strokeWidth={1.9} className="h-6 w-6 sm:h-7 sm:w-7"/><span className="pointer-events-none absolute right-full mr-3 hidden whitespace-nowrap rounded-md border border-black/10 bg-white px-3 py-2 text-xs font-bold text-[#171717] shadow-lg sm:group-hover:block">Ask about Shashank</span></button>;
}

export function PortfolioChat() {
  const [messages, setMessages] = useState<ChatMessage[]>([]), [input, setInput] = useState(""), [loading, setLoading] = useState(false), [error, setError] = useState<{ code: string; message: string } | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null), logRef = useRef<HTMLDivElement>(null), limit = 1200;
  useEffect(() => { const focus = () => textareaRef.current?.focus({ preventScroll: true }); window.addEventListener("portfolio-chat-focus", focus); return () => window.removeEventListener("portfolio-chat-focus", focus); }, []);
  useEffect(() => { logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: "smooth" }); }, [messages, loading, error]);
  const send = async (prompt = input) => { const clean = prompt.trim(); if (!clean || loading || clean.length > limit) return; const next: ChatMessage[] = [...messages, { role: "user", content: clean } as ChatMessage].slice(-10); setMessages(next); setInput(""); setError(null); setLoading(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ messages: next }) }); const data = await response.json() as { answer?: string; error?: { code?: string; message?: string } }; if (!response.ok || !data.answer) throw Object.assign(new Error(data.error?.message || "The assistant is unavailable."), { code: data.error?.code || "CHAT_ERROR" }); setMessages(current => [...current, { role: "assistant", content: data.answer! }]); } catch (caught) { const failure = caught as Error & { code?: string }; setError({ code: failure.code || "NETWORK_ERROR", message: failure.message || "Could not reach the assistant." }); } finally { setLoading(false); } };
  const empty = messages.length === 0 && !error;
  return <section id="chat" data-section-theme="zinc" className="relative scroll-mt-20 overflow-hidden border-t-2 border-[#f04b23] bg-[#f3f1eb] pb-10 pt-24 text-[#191816] md:py-20">
    <div className="pointer-events-none absolute inset-0 opacity-[.16] [background-image:linear-gradient(rgba(25,24,22,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(25,24,22,.12)_1px,transparent_1px)] [background-size:56px_56px] [mask-image:linear-gradient(to_right,black,transparent_72%)]"/>
    <div className="container relative z-10 mx-auto px-4 sm:px-6"><div className="mx-auto max-w-6xl"><header className="mb-5 flex flex-col justify-between gap-3 border-b border-black/15 pb-5 sm:mb-8 sm:flex-row sm:items-end sm:gap-5 sm:pb-6"><div><span className="font-mono text-[10px] font-bold uppercase tracking-[.22em] text-[#b93617]">AI portfolio assistant</span><h2 className="mt-2 max-w-2xl text-4xl font-bold leading-[1.02] tracking-tight sm:mt-3 sm:text-5xl lg:text-6xl">What would you like to know?</h2></div><span className="inline-flex w-fit items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-black/55"><i className="h-2 w-2 rounded-full bg-emerald-600"/>Online · Portfolio knowledge</span></header>
      <div className="grid overflow-hidden border border-black/15 bg-[#e9e6df] shadow-[0_24px_70px_rgba(50,38,29,.13)] lg:grid-cols-[280px_1fr]"><aside className="border-b border-black/10 bg-[#edeae3] p-3 sm:p-5 lg:border-b-0 lg:border-r lg:p-6"><p className="mb-4 hidden text-xs font-bold uppercase tracking-[.12em] text-black/50 lg:block">Recruiter shortcuts</p><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{starters.map((item, index) => <button key={item.label} type="button" onClick={() => send(item.prompt)} disabled={loading} className="group min-h-12 border border-black/10 bg-[#f7f5f0] p-2 text-left transition hover:border-[#f04b23]/60 hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23] disabled:opacity-50 sm:min-h-16 sm:p-3"><span className="font-mono text-[8px] text-[#b93617] sm:text-[9px]">0{index + 1}</span><span className="mt-0.5 block text-[11px] font-bold leading-4 sm:mt-1 sm:text-sm">{item.label}</span></button>)}</div></aside>
        <div className="min-w-0 bg-white"><div ref={logRef} role="log" aria-live="polite" aria-label="Conversation" className={`${empty ? "h-[210px]" : "h-[300px]"} overflow-y-auto p-4 transition-[height] sm:h-[390px] sm:p-7 lg:h-[430px] lg:p-9`}>{empty ? <div className="flex h-full items-center"><div className="max-w-lg"><span className="grid h-9 w-9 place-items-center rounded-xl border border-[#f04b23]/25 bg-[#fff4ef] text-[#d53c19] sm:h-10 sm:w-10"><MessageCircle className="h-4 w-4 sm:h-5 sm:w-5"/></span><h3 className="mt-3 text-lg font-bold sm:mt-4 sm:text-2xl">Ask about experience, projects, or technical fit.</h3><p className="mt-1.5 text-xs leading-5 text-black/55 sm:mt-2 sm:text-sm sm:leading-6">Choose a shortcut or write your own question below.</p></div></div> : <div className="space-y-5">{messages.map((message,index) => <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[90%] px-4 py-3 text-sm leading-6 sm:max-w-[76%] ${message.role === "user" ? "rounded-[1rem_1rem_.2rem_1rem] bg-[#1d1c1a] text-white" : "border-l-2 border-[#f04b23] bg-[#f6f3ed] text-black/80"}`}>{message.role === "assistant" && <span className="mb-2 flex items-center gap-2 font-mono text-[9px] font-bold uppercase tracking-[.12em] text-[#b93617]"><Bot className="h-3.5 w-3.5"/>Shashank’s portfolio</span>}<SafeText text={message.content}/></div></div>)}{loading && <div className="flex items-center gap-3 text-sm text-black/55"><span className="flex gap-1"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#f04b23]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#f04b23] [animation-delay:120ms]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#f04b23] [animation-delay:240ms]"/></span>Reviewing Shashank’s portfolio…</div>}</div>}{error && <div role="alert" className="mt-5 border border-[#f04b23]/30 bg-[#fff4ef] p-4 text-sm"><strong className="block text-[#b83216]">{error.code === "CHAT_NOT_CONFIGURED" ? "Assistant unavailable" : "Response interrupted"}</strong><p className="mt-1 text-black/65">{error.code === "CHAT_NOT_CONFIGURED" ? "Chat has not been enabled on this deployment. You can still contact Shashank directly by email or LinkedIn." : error.message}</p>{error.code === "CHAT_NOT_CONFIGURED" ? <div className="mt-3 flex gap-4"><a href="mailto:shashankpendyala3549@gmail.com" className="font-bold text-[#b83216] underline underline-offset-2">Email</a><a href="https://www.linkedin.com/in/shashank35i/" target="_blank" rel="noopener noreferrer" className="font-bold text-[#b83216] underline underline-offset-2">LinkedIn</a></div> : <button type="button" onClick={() => { setError(null); const last = [...messages].reverse().find(item => item.role === "user"); if (last) send(last.content); }} className="mt-3 inline-flex items-center gap-2 font-bold text-[#b83216]"><RotateCcw className="h-4 w-4"/>Retry</button>}</div>}</div>
          <div className="border-t border-black/10 bg-[#faf9f6] p-3 sm:p-4"><div className="flex items-end gap-2 rounded-2xl border border-black/15 bg-white p-2 shadow-[0_8px_26px_rgba(45,34,26,.08)] focus-within:border-[#f04b23] focus-within:shadow-[0_0_0_3px_rgba(240,75,35,.1)]"><textarea ref={textareaRef} value={input} maxLength={limit} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }} rows={1} aria-label="Ask about Shashank" placeholder="Ask about Shashank’s work…" className="max-h-32 min-h-11 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm leading-6 outline-none placeholder:text-black/35"/><button type="button" onClick={() => send()} disabled={!input.trim() || loading} aria-label="Send message" className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#f04b23] text-white transition hover:bg-[#dc401d] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23] disabled:opacity-35"><ArrowUp className="h-5 w-5"/></button></div><div className="mt-2 flex justify-between px-2 text-[9px] text-black/45"><span>AI responses may be imperfect.</span><span>{input.length}/{limit}</span></div></div></div>
      </div>
    </div></div>
  </section>;
}
