import { useEffect, useRef, useState } from "react";
import { ArrowUp, Bot, MessageCircle, RotateCcw, Sparkles } from "lucide-react";
import type { ChatMessage } from "@shared/portfolio-chat";

const starters = ["Why is Shashank a strong Java backend candidate?", "Explain OpsPilot-AI in 30 seconds.", "What did he improve at 9X IT Solutions?", "Which projects show Android experience?"];

function SafeText({ text }: { text: string }) {
  const renderInline = (content: string) => content.split(/(\*\*[^*]+\*\*|\[[^\]]+\]\([^)]+\))/g).map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>;
    const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (link) {
      try { const url = new URL(link[2]); if (!["http:", "https:", "mailto:"].includes(url.protocol)) throw new Error("unsafe protocol"); const external = url.protocol === "http:" || url.protocol === "https:"; return <a key={index} href={url.href} target={external ? "_blank" : undefined} rel={external ? "noopener noreferrer" : undefined} className="font-semibold text-[#b83216] underline decoration-[#f04b23]/40 underline-offset-2 hover:decoration-[#f04b23] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23]">{link[1]}</a>; } catch { return <span key={index}>{part}</span>; }
    }
    return <span key={index}>{part}</span>;
  });
  const lines = text.split("\n");
  return <div className="space-y-2">{lines.map((line, index) => {
    const bullet = /^[-*]\s+/.test(line); const content = line.replace(/^[-*]\s+/, "");
    const node = <>{renderInline(content)}</>;
    return bullet ? <div key={index} className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#f04b23]"/><p>{node}</p></div> : line ? <p key={index}>{node}</p> : <div key={index} className="h-1"/>;
  })}</div>;
}

export function ChatLauncher() {
  const activate = () => { const section = document.getElementById("chat"); const near = section && section.getBoundingClientRect().top < 120 && section.getBoundingClientRect().bottom > 180; if (!near) section?.scrollIntoView({ behavior: "smooth", block: "start" }); window.setTimeout(() => window.dispatchEvent(new Event("portfolio-chat-focus")), near ? 0 : 700); };
  return <button type="button" onClick={activate} aria-label="Ask about Shashank" title="Ask about Shashank" className="group fixed bottom-[calc(1rem+env(safe-area-inset-bottom))] right-4 z-[70] grid h-14 w-14 place-items-center rounded-[1.1rem] bg-[#f04b23] text-white shadow-[0_14px_40px_rgba(240,75,35,.4)] transition hover:-translate-y-1 hover:bg-[#d93f1b] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f04b23] sm:bottom-[calc(1.5rem+env(safe-area-inset-bottom))] sm:right-6"><span className="absolute inset-0 -z-10 animate-[ping_1.4s_ease-out_1] rounded-[1.1rem] bg-[#f04b23]/40"/><MessageCircle className="h-6 w-6"/><span className="pointer-events-none absolute right-full mr-3 hidden whitespace-nowrap border border-black/10 bg-[#f5f4ef] px-3 py-2 text-xs font-bold text-[#171717] shadow-lg group-hover:block">Ask about Shashank</span></button>;
}

export function PortfolioChat() {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<{ code: string; message: string } | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null); const logRef = useRef<HTMLDivElement>(null); const limit = 1200;
  useEffect(() => { const focus = () => textareaRef.current?.focus({ preventScroll: true }); window.addEventListener("portfolio-chat-focus", focus); return () => window.removeEventListener("portfolio-chat-focus", focus); }, []);
  useEffect(() => { logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: "smooth" }); }, [messages, loading, error]);
  const send = async (prompt = input) => { const clean = prompt.trim(); if (!clean || loading || clean.length > limit) return; const userMessage: ChatMessage = { role: "user", content: clean }; const next: ChatMessage[] = [...messages, userMessage].slice(-10); setMessages(next); setInput(""); setError(null); setLoading(true);
    try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ messages: next }) }); const data = await response.json() as { answer?: string; error?: { code?: string; message?: string } }; if (!response.ok || !data.answer) throw Object.assign(new Error(data.error?.message || "The assistant is unavailable."), { code: data.error?.code || "CHAT_ERROR" }); setMessages(current => [...current, { role: "assistant", content: data.answer! }]); }
    catch (caught) { const failure = caught as Error & { code?: string }; setError({ code: failure.code || "NETWORK_ERROR", message: failure.message || "Could not reach the assistant." }); } finally { setLoading(false); }
  };
  return <section id="chat" data-section-theme="zinc" className="relative scroll-mt-20 overflow-hidden bg-[#f5f4ef] py-20 text-[#181716] md:py-28">
    <div className="pointer-events-none absolute inset-0 opacity-45 [background-image:radial-gradient(#f04b23_1px,transparent_1px)] [background-size:34px_34px] [mask-image:radial-gradient(circle_at_80%_20%,black,transparent_58%)]"/><div className="pointer-events-none absolute -right-32 top-12 h-96 w-96 rounded-full border border-[#f04b23]/25"/><div className="pointer-events-none absolute -right-16 top-28 h-64 w-64 rounded-full border border-[#f04b23]/20"/>
    <div className="container relative z-10 mx-auto px-4 sm:px-6"><header className="mx-auto mb-10 max-w-6xl border-t border-black/20 pt-6"><div className="grid gap-7 lg:grid-cols-[1fr_.8fr]"><div><span className="font-mono text-xs uppercase tracking-[.24em] text-[#c63716]">07 / Portfolio assistant</span><h2 className="mt-5 text-5xl font-bold leading-[.95] tracking-tight sm:text-7xl">Ask about<br/>Shashank.</h2></div><div className="self-end"><p className="max-w-xl text-base leading-7 text-black/70">Fast answers grounded in Shashank’s verified portfolio and resume—not a general-purpose chatbot.</p><div className="mt-5 flex flex-wrap gap-x-3 gap-y-1 font-mono text-[9px] font-bold uppercase tracking-[.16em] text-black/55"><span>Groq inference</span><span>·</span><span>Portfolio context</span><span>·</span><span>Private server key</span></div></div></div></header>
      <div className="mx-auto max-w-6xl"><div className="mb-5 flex gap-2 overflow-x-auto pb-2">{starters.map(prompt => <button key={prompt} type="button" onClick={() => send(prompt)} disabled={loading} className="shrink-0 border border-black/15 bg-white/55 px-4 py-2.5 text-left text-xs font-semibold transition hover:border-[#f04b23] hover:text-[#c63716] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23] disabled:opacity-50">{prompt}</button>)}</div>
        <div className="overflow-hidden border border-black/15 bg-white shadow-[0_30px_90px_rgba(61,43,30,.12)]"><div ref={logRef} role="log" aria-live="polite" aria-label="Conversation" className="h-[420px] overflow-y-auto p-5 sm:h-[480px] sm:p-8">
          {messages.length === 0 && !error ? <div className="flex h-full min-h-64 items-center justify-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f04b23] text-white"><Sparkles className="h-6 w-6"/></div><h3 className="mt-5 text-2xl font-bold">Start with a project, skill, or role.</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-black/55">Try a prompt above or ask what makes Shashank a fit for your engineering team.</p></div></div> : <div className="space-y-5">{messages.map((message,index) => <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] px-4 py-3 text-sm leading-6 sm:max-w-[72%] ${message.role === "user" ? "rounded-[1.2rem_1.2rem_.25rem_1.2rem] bg-[#181716] text-white" : "border-l-2 border-[#f04b23] bg-[#f7f3ee] text-black/80"}`}>{message.role === "assistant" && <span className="mb-2 flex items-center gap-2 font-mono text-[9px] font-bold uppercase tracking-[.14em] text-[#c63716]"><Bot className="h-3.5 w-3.5"/> Portfolio assistant</span>}<SafeText text={message.content}/></div></div>)}{loading && <div className="flex items-center gap-3 text-sm text-black/55"><span className="flex gap-1"><i className="h-2 w-2 animate-bounce rounded-full bg-[#f04b23]"/><i className="h-2 w-2 animate-bounce rounded-full bg-[#f04b23] [animation-delay:120ms]"/><i className="h-2 w-2 animate-bounce rounded-full bg-[#f04b23] [animation-delay:240ms]"/></span>Reading portfolio context…</div>}</div>}
          {error && <div role="alert" className="mt-5 border border-[#f04b23]/30 bg-[#fff4ef] p-4 text-sm"><strong className="block text-[#b83216]">{error.code === "CHAT_NOT_CONFIGURED" ? "Assistant unavailable" : "Response interrupted"}</strong><p className="mt-1 text-black/65">{error.code === "CHAT_NOT_CONFIGURED" ? "Chat has not been enabled on this deployment. You can still contact Shashank directly by email or LinkedIn." : error.message}</p>{error.code === "CHAT_NOT_CONFIGURED" ? <div className="mt-3 flex flex-wrap gap-4"><a href="mailto:shashankpendyala3549@gmail.com" className="font-bold text-[#b83216] underline underline-offset-2 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23]">Email Shashank</a><a href="https://www.linkedin.com/in/shashank35i/" target="_blank" rel="noopener noreferrer" className="font-bold text-[#b83216] underline underline-offset-2 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23]">LinkedIn</a></div> : <button type="button" onClick={() => { setError(null); const last = [...messages].reverse().find(item => item.role === "user"); if (last) send(last.content); }} className="mt-3 inline-flex items-center gap-2 font-bold text-[#b83216] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23]"><RotateCcw className="h-4 w-4"/>Retry</button>}</div>}
        </div><div className="border-t border-black/10 bg-[#fbfaf7] p-3 sm:p-5"><div className="flex items-end gap-3 rounded-[1.6rem] border border-[#f04b23]/35 bg-white p-2.5 shadow-[0_0_0_4px_rgba(240,75,35,.06),0_12px_35px_rgba(240,75,35,.1)]"><textarea ref={textareaRef} value={input} maxLength={limit} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }} rows={1} aria-label="Ask about Shashank" placeholder="Ask about Shashank’s projects, Java experience, or availability…" className="max-h-36 min-h-11 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm leading-6 text-black outline-none placeholder:text-black/40"/><button type="button" onClick={() => send()} disabled={!input.trim() || loading} aria-label="Send message" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#f04b23] text-white transition hover:bg-[#d93f1b] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f04b23] disabled:cursor-not-allowed disabled:opacity-35"><ArrowUp className="h-5 w-5"/></button></div><div className="mt-3 flex items-start justify-between gap-4 px-2 text-[10px] text-black/50"><p>Answers use verified portfolio context. AI responses may be imperfect.</p><span className={input.length > limit * .85 ? "font-bold text-[#c63716]" : ""}>{input.length}/{limit}</span></div></div></div>
      </div></div>
  </section>;
}
